using System.Collections;
using System.Collections.Generic;
using UnityEngine;

[System.Serializable]
public class PlayerData
{
    public int[] resources;
    public int[] autoResources;

    public PlayerData(PlayerManager player)
    {
        resources = player.playerResouces;
        autoResources = player.playerAutoGeneratedResources;
    }
}
